#:kivy 2.1.0
MDScreenManager:
    MDScreen:
        MDFloatLayout:
            spacing: "15dp"
            MDTextField:
                hint_text: "Username"
                size_hint: 0.5, None
                # size: 100, 50
                pos_hint: {"x": 0.25, "y": 0.5}
            MDTextField:
                hint_text: "Password"
                size_hint: 0.5, None
                # size: 100, 50
                pos_hint: {"x": 0.25, "y": 0.4}