#:kivy 2.1.0
#:include ./templates/attendance_screen.kv
#:include ./templates/login_screen.kv

MDScreenManager:
    id: screen_manager
    LoginScreen:
        id: login_screen
        name: "login_screen"
        manager: screen_manager
    # GPSScreen:
    #     id: gps_screen
    #     name: "gps_screen"
    #     manager: screen_manager
    # AttendanceScreen:
    #     id: attendance_screen
    #     manager: screen_manager
    #     name: "attendance_screen"
